// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: proto/proto-file.proto

package HandIn2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitialAgreement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P []byte `protobuf:"bytes,1,opt,name=P,proto3" json:"P,omitempty"`  //Large prime
	Q []byte `protobuf:"bytes,2,opt,name=Q,proto3" json:"Q,omitempty"`  //large prime such that q % p-1 = 0
	G int64  `protobuf:"varint,3,opt,name=G,proto3" json:"G,omitempty"` //rand int with some restrictions
}

func (x *InitialAgreement) Reset() {
	*x = InitialAgreement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialAgreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialAgreement) ProtoMessage() {}

func (x *InitialAgreement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialAgreement.ProtoReflect.Descriptor instead.
func (*InitialAgreement) Descriptor() ([]byte, []int) {
	return file_proto_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *InitialAgreement) GetP() []byte {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *InitialAgreement) GetQ() []byte {
	if x != nil {
		return x.Q
	}
	return nil
}

func (x *InitialAgreement) GetG() int64 {
	if x != nil {
		return x.G
	}
	return 0
}

type Commitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H []byte `protobuf:"bytes,4,opt,name=H,proto3" json:"H,omitempty"` //h = g^a % p
}

func (x *Commitment) Reset() {
	*x = Commitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commitment) ProtoMessage() {}

func (x *Commitment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commitment.ProtoReflect.Descriptor instead.
func (*Commitment) Descriptor() ([]byte, []int) {
	return file_proto_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *Commitment) GetH() []byte {
	if x != nil {
		return x.H
	}
	return nil
}

type CommitmentOpener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roll    int64 `protobuf:"varint,1,opt,name=Roll,proto3" json:"Roll,omitempty"`
	RandInt int64 `protobuf:"varint,2,opt,name=RandInt,proto3" json:"RandInt,omitempty"`
}

func (x *CommitmentOpener) Reset() {
	*x = CommitmentOpener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitmentOpener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentOpener) ProtoMessage() {}

func (x *CommitmentOpener) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentOpener.ProtoReflect.Descriptor instead.
func (*CommitmentOpener) Descriptor() ([]byte, []int) {
	return file_proto_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *CommitmentOpener) GetRoll() int64 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *CommitmentOpener) GetRandInt() int64 {
	if x != nil {
		return x.RandInt
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAcknowledged bool `protobuf:"varint,1,opt,name=IsAcknowledged,proto3" json:"IsAcknowledged,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetIsAcknowledged() bool {
	if x != nil {
		return x.IsAcknowledged
	}
	return false
}

type RealRoll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAcknowledged bool   `protobuf:"varint,1,opt,name=IsAcknowledged,proto3" json:"IsAcknowledged,omitempty"`
	IsGuessed      bool   `protobuf:"varint,2,opt,name=isGuessed,proto3" json:"isGuessed,omitempty"`
	DieRoll        []byte `protobuf:"bytes,3,opt,name=DieRoll,proto3" json:"DieRoll,omitempty"`
}

func (x *RealRoll) Reset() {
	*x = RealRoll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealRoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealRoll) ProtoMessage() {}

func (x *RealRoll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealRoll.ProtoReflect.Descriptor instead.
func (*RealRoll) Descriptor() ([]byte, []int) {
	return file_proto_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *RealRoll) GetIsAcknowledged() bool {
	if x != nil {
		return x.IsAcknowledged
	}
	return false
}

func (x *RealRoll) GetIsGuessed() bool {
	if x != nil {
		return x.IsGuessed
	}
	return false
}

func (x *RealRoll) GetDieRoll() []byte {
	if x != nil {
		return x.DieRoll
	}
	return nil
}

var File_proto_proto_file_proto protoreflect.FileDescriptor

var file_proto_proto_file_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3c, 0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x50, 0x12, 0x0c, 0x0a, 0x01, 0x51, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x51, 0x12,
	0x0c, 0x0a, 0x01, 0x47, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x47, 0x22, 0x1a, 0x0a,
	0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x48,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x48, 0x22, 0x40, 0x0a, 0x10, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x52, 0x6f, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f, 0x6c,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x52, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x03, 0x41,
	0x63, 0x6b, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x73, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x49, 0x73, 0x41, 0x63,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x22, 0x6a, 0x0a, 0x08, 0x52, 0x65,
	0x61, 0x6c, 0x52, 0x6f, 0x6c, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x73, 0x41, 0x63, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x49, 0x73, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x73, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x44, 0x69, 0x65, 0x52, 0x6f, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x44,
	0x69, 0x65, 0x52, 0x6f, 0x6c, 0x6c, 0x32, 0xb8, 0x01, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x44, 0x69, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0f,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x41, 0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x41,
	0x67, 0x72, 0x65, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x6b, 0x12, 0x3a, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x72,
	0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x52, 0x6f, 0x6c,
	0x6c, 0x42, 0x0e, 0x5a, 0x0c, 0x53, 0x65, 0x63, 0x31, 0x2f, 0x48, 0x61, 0x6e, 0x64, 0x49, 0x6e,
	0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proto_file_proto_rawDescOnce sync.Once
	file_proto_proto_file_proto_rawDescData = file_proto_proto_file_proto_rawDesc
)

func file_proto_proto_file_proto_rawDescGZIP() []byte {
	file_proto_proto_file_proto_rawDescOnce.Do(func() {
		file_proto_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proto_file_proto_rawDescData)
	})
	return file_proto_proto_file_proto_rawDescData
}

var file_proto_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proto_file_proto_goTypes = []interface{}{
	(*InitialAgreement)(nil), // 0: proto.InitialAgreement
	(*Commitment)(nil),       // 1: proto.Commitment
	(*CommitmentOpener)(nil), // 2: proto.CommitmentOpener
	(*Ack)(nil),              // 3: proto.Ack
	(*RealRoll)(nil),         // 4: proto.RealRoll
}
var file_proto_proto_file_proto_depIdxs = []int32{
	0, // 0: proto.RollingDieService.SetupAgreements:input_type -> proto.InitialAgreement
	1, // 1: proto.RollingDieService.SendCommitment:input_type -> proto.Commitment
	2, // 2: proto.RollingDieService.OpenCommitment:input_type -> proto.CommitmentOpener
	3, // 3: proto.RollingDieService.SetupAgreements:output_type -> proto.Ack
	3, // 4: proto.RollingDieService.SendCommitment:output_type -> proto.Ack
	4, // 5: proto.RollingDieService.OpenCommitment:output_type -> proto.RealRoll
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_file_proto_init() }
func file_proto_proto_file_proto_init() {
	if File_proto_proto_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_proto_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialAgreement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitmentOpener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealRoll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proto_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_file_proto_goTypes,
		DependencyIndexes: file_proto_proto_file_proto_depIdxs,
		MessageInfos:      file_proto_proto_file_proto_msgTypes,
	}.Build()
	File_proto_proto_file_proto = out.File
	file_proto_proto_file_proto_rawDesc = nil
	file_proto_proto_file_proto_goTypes = nil
	file_proto_proto_file_proto_depIdxs = nil
}
